spring:
  config:
    activate:
      on-profile: proddb
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

