spring:
  config:
    activate:
      on-profile: common
  application:
    name: jwtsecurity-service
  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: 8601

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: 'threaddump,heapdump'

security:
  token:
    refresh:
      secret: thisisasecretkeythisisasecretkeythisisasecretkey
      expired: 300
    access:
      secret: thisisasecretkeythisisasecretkeythisisasecretkey
      expired: 120
  login:
    url: /api/auth/login
    method: POST
    username_parameter: email
    password_parameter: password
    refresh_token_parameter: refreshToken




logging:
  level:
    org.hibernate.type: trace

